/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kas;

import javax.swing.JOptionPane;

/**
 *
 * @author muham
 */
public class login extends javax.swing.JFrame {

    private Object fajri_username;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fajri_username = new javax.swing.JTextField();
        fajri_password = new javax.swing.JPasswordField();
        fajri_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("Data Keuangan KAS");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 103, 211, 28));

        fajri_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fajri_username.setText("UserName");
        fajri_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(fajri_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 162, 211, 43));

        fajri_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fajri_password.setText("jPassword");
        fajri_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fajri_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(fajri_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 217, 211, 43));

        fajri_login.setText("LOGIN");
        fajri_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fajri_loginActionPerformed(evt);
            }
        });
        jPanel1.add(fajri_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 278, 138, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fajri_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fajri_loginActionPerformed
        // TODO add your handling code here:
        String username="Bendahara";
        String password="2019804091";
        if(username.equalsIgnoreCase(fajri_username.getText())&&
            password.equalsIgnoreCase(fajri_password.getText())){
            this.setVisible(false);
            new MenuUtama().setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN");
            dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "MAAF USER DAN PASSWORD ANDA SALAH", "Error",
                        JOptionPane.ERROR_MESSAGE);
            fajri_username.setText("UserName");
            fajri_password.setText("password");
            fajri_username.requestFocus();
        }
    }    
    }//GEN-LAST:event_fajri_loginActionPerformed

    private void fajri_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fajri_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fajri_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fajri_login;
    private javax.swing.JPasswordField fajri_password;
    private javax.swing.JTextField fajri_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
