/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author muham
 */
public class TableMahasiswa extends javax.swing.JFrame {
 private Connection con;
    private Statement stat;
    private ResultSet res;
    /**
     * Creates new form TableMahasiswa
     */
    public TableMahasiswa() {
        initComponents();
        initComponents();
        setTitle("TABLE DATA MAHASISWA");
        koneksi ();
        tabel ();
        fajri_table.setAutoCreateRowSorter(true);
    }
private void koneksi (){
        try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasikelas", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}
        }
        
        private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("Nim");
        t.addColumn("Nama");
        t.addColumn("Jenis Kelamin");
        t.addColumn("No HP");
        t.addColumn("Alamat");
        fajri_table.setModel(t); try{ res= stat.executeQuery("select * from mahasiswa");
while (res.next()) {
    t.addRow(new Object[]{ res.getString("Nim"),
      res.getString("Nama"),
      res.getString("JenisKelamin"),
      res.getString("NoHp"),
      res.getString("Alamat")
        });
    }
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
}    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fajri_table = new javax.swing.JTable();
        fajri_mahasiswa = new javax.swing.JButton();
        fajri_uangkas = new javax.swing.JButton();
        fajri_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TABLE MAHASISWA");

        fajri_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(fajri_table);

        fajri_mahasiswa.setText("Pilih Mahasiswa");
        fajri_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fajri_mahasiswaActionPerformed(evt);
            }
        });

        fajri_uangkas.setText("Plilih UangKas");
        fajri_uangkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fajri_uangkasActionPerformed(evt);
            }
        });

        fajri_back.setText("BACK");
        fajri_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fajri_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(469, 469, 469))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(fajri_mahasiswa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fajri_uangkas)
                                .addGap(102, 102, 102)
                                .addComponent(fajri_back))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(263, 263, 263))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fajri_mahasiswa)
                    .addComponent(fajri_uangkas)
                    .addComponent(fajri_back))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Mahasiswa data = new  Mahasiswa();
    private void fajri_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fajri_mahasiswaActionPerformed
        // TODO add your handling code here:
         int index = fajri_table.getSelectedRow();
        
        TableModel model = fajri_table.getModel();
        
        String nim = model.getValueAt(index, 0).toString();
        String nama = model.getValueAt(index, 1).toString();
        String jk = model.getValueAt(index, 2).toString();
        String nohp = model.getValueAt(index, 3).toString();
        String alamat = model.getValueAt(index, 4).toString();
      
       
        data.setVisible(true);
        data.pack();
        data.setLocationRelativeTo(null);
        data.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        data.fajri_nim.setText(nim);
        data.fajri_nama.setText(nama);
        data.fajri_jk.setSelectedItem(jk);
        data.fajri_nohp.setText(nohp);
        data.fajri_alamat.setText(alamat);
        dispose();
    }//GEN-LAST:event_fajri_mahasiswaActionPerformed
UangKas mahasiswa = new  UangKas();
    private void fajri_uangkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fajri_uangkasActionPerformed
        // TODO add your handling code here:
         int index = fajri_table.getSelectedRow();
        
        TableModel model = fajri_table.getModel();
        
        String nama = model.getValueAt(index, 1).toString();
      
       
        mahasiswa.setVisible(true);
        mahasiswa.pack();
        mahasiswa.setLocationRelativeTo(null);
        mahasiswa.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        mahasiswa.fajri_nama.setText(nama);
        dispose();
    }//GEN-LAST:event_fajri_uangkasActionPerformed

    private void fajri_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fajri_backActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_fajri_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fajri_back;
    private javax.swing.JButton fajri_mahasiswa;
    private javax.swing.JTable fajri_table;
    private javax.swing.JButton fajri_uangkas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
